### ISSUE TITLE
eloverblik.nim(3, 36) Error: cannot open file: nmqtt

### ISSUE THREAD

**Issue by dkjsj** [ThomasTJdev/nim_eloverblik_api#1]
Hi

Get's the error when compiling (nim c -d:ssl -d:release eloverblik.nim):
eloverblik.nim(3, 36) Error: cannot open file: nmqtt

Can you recommend an nMQTT client on Debian Linux

**Comment by ThomasTJdev** [comment]
Hi @dkjsj 

Run:
```nim
nimble install https://github.com/zevv/nmqtt
```

**Comment by ThomasTJdev** [comment]
> Can you recommend an nMQTT client on Debian Linux

Absolutely - go with: https://github.com/zevv/nmqtt

The new version of `nmqtt` includes both a client for publishing and subscribing. You need to install the `master`:
```nim
$ git clone https://github.com/zevv/nmqtt
$ cd nmqtt
$ nimble install
# And then:
$ nmqttpub -t MyTopic -m MyMsg
$ nmqttsub -t MyTopic
```

**Comment by dkjsj** [comment]
Great; The host machine is running some old versions of nim - so are embedding into a Docker Container instead:

From Dockerfile:

```
FROM nimlang/nim:latest AS build

WORKDIR /usr/src/app

RUN nimble refresh && nimble install nmqtt

RUN cd /usr/src/app \
    && git clone https://github.com/ThomasTJdev/nim_eloverblik_api \
    && cd /usr/src/app/nim_eloverblik_api \
    && nim c -d:ssl -d:release eloverblik.nim_ 
```


But it fails the build part with:

```
/usr/src/app/nim_eloverblik_api/eloverblik.nim(103, 49) template/generic instantiation of `async` from here
/usr/src/app/nim_eloverblik_api/eloverblik.nim(116, 12) Error: attempting to call undeclared routine: 'disconnect'
```

Any ideas?

**Comment by ThomasTJdev** [comment]
Yeah - it's using an old version of nmqtt. Can you try to install nmqtt from master? I'll look into it tomorrow.

Nmqtt from master:
```nim
$ git clone https://github.com/zevv/nmqtt
$ cd nmqtt
$ nimble install
```

**Comment by dkjsj** [comment]
A little better; Might be my nimble experience:

```
FROM nimlang/nim:latest AS build

## set working directory
WORKDIR /usr/src/app

# install dependencies, bundle assets, compile
RUN nimble refresh

RUN git clone https://github.com/zevv/nmqtt \
    && cd nmqtt \
    && nimble -y install

# Get ElOverblik API
RUN git clone https://github.com/ThomasTJdev/nim_eloverblik_api && cd nim_eloverblik_api \
    && nim c -d:ssl -d:release eloverblik.nim 

```

Fails with:

`/usr/src/app/nim_eloverblik_api/eloverblik.nim(3, 36) Error: cannot open file: nmqtt`

Seems to be som path issues?

**Comment by dkjsj** [comment]
FYI : Just tried to use nmqtt_pub and nmqtt_sub from the Docker Containe - which works. So path's seems to be working.

**Comment by ThomasTJdev** [comment]
Hi @dkjsj 

You are doing it correctly - I had not updated the `nmqtt.nimble` file to include the library, only the binaries was included. I have committed the changes to the master branch. Please run the following again, and then you can import `nmqtt`:
```
$ git clone https://github.com/zevv/nmqtt
$ cd nmqtt
$ nimble install
```

**Comment by dkjsj** [comment]
> Hi @dkjsj
> 
> You are doing it correctly - I had not updated the `nmqtt.nimble` file to include the library, only the binaries was included. I have committed the changes to the master branch. Please run the following again, and then you can import `nmqtt`:
> 
> ```
> $ git clone https://github.com/zevv/nmqtt
> $ cd nmqtt
> $ nimble install
> ```

It compiles perfectly now. Thanks. The following Docker Buildfile is used:

```
###############
# BUILD IMAGE #
###############
FROM nimlang/nim:latest AS build

## set working directory
WORKDIR /usr/src/app

# install dependencies, bundle assets, compile
RUN nimble refresh

# Get Master from GitHub
RUN git clone https://github.com/zevv/nmqtt \
    && cd nmqtt \
    && nimble -y install 
  
ENV PATH=:/root/.nimble/bin:/nim/bin/:$PATH	

# Get ElOverblik API
RUN git clone https://github.com/ThomasTJdev/nim_eloverblik_api && cd nim_eloverblik_api \
    && nim c -d:ssl -d:release eloverblik.nim 
```

Will share the final Docker Buildfile when ready...

**Comment by ThomasTJdev** [comment]
> Will share the final Docker Buildfile when ready...

Thanks! :smiley:
